config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :servers, only: [:new, :create]
  resources :menu_items
  resources :orders
  resources :customers
  resources :admins

  get '/servers/log_in'   => "servers#log_in", as: :log_in

  post '/sessions'        => "sessions#create", as: :creation
  delete '/sessions'      => "sessions#destroy", as: :deletion
  get '/servers/profile'  => "servers#profile", as: :profile

end

app/models/customer.rb
class Customer <ActiveRecord::Base

  belongs_to :server
  has_many :orders
  has_many :menu_items, :through => :orders

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base

  has_many :orders
  has_many :customers, :through => :orders

end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :server
  belongs_to :menu_item
  belongs_to :customer

end

app/models/server.rb
class Server < ActiveRecord::Base
  has_secure_password

  has_many :orders
  has_many :customers
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @menu_items = MenuItem.all
  end

  def show
    @menu_item = MenuItem.find params[:id]
  end

  def edit
    @menu_item = MenuItem.find params[:id]
  end

  def update
    menu_item = MenuItem.find params[:id]
    menu_item.update menu_item_params
    redirect_to menu_items_path
  end

  def new
    @menu_item = MenuItem.new
  end

  def create
    menu_item = MenuItem.create menu_item_params.merge({server_id: current_server.id})
    redirect_to profile_path
  end

  def destroy
    menu_item = MenuItem.find params[:id]
    menu_item.destroy
    redirect_to profile_path
  end

  private

  def menu_item_params
    params.require(:menu_item).permit(:name, :description, :price)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

#   rescue_from 'ActiveRecord::InvalidForeignKey' do
#   # Flash and render, render API json error... whatever
# end




end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :get_server_or_redirect_to_log_in


  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find params[:id]
    @order = Order.new
  end

  def edit
    @customer = Customer.find params[:id]
  end

  def update
    customer = Customer.find params[:id]
    customer.update customer_params
    redirect_to customers_path
  end

  def new
    @customer = Customer.new
  end

  def create
    customer = Customer.create customer_params
    redirect_to customers_path
  end

  def destroy
    customer = Customer.find params[:id]
    # customer.destroy
    # redirect_to customers_path

    # tried but didn't work
    # customer.destroy[:customer.id]
    # customer.destroy(customer_params)


    if customer.orders.any?
      flash[:error] = "Can't delete customer - open orders"
      redirect_to customers_path
    else
      customer.destroy!
      flash[:success] = "Customer has paid - they can leave"
      redirect_to customers_path
    end

  end

  private

  def customer_params
    params.require(:customer).permit(:server_id, :order_id, :table_number, :seat_number, :has_paid)
  end

  def get_server_or_redirect_to_log_in

    if session[:server_id]
      @server = Server.find session[:server_id]
    else
      redirect_to log_in_path
    end

  end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

  before_action :admin_or_redirect_to_log_in


  def index
    @menu_items = MenuItem.all
  end

  def create
    menu_item = MenuItem.create menu_item_params
    redirect_to menu_items_path
  end

  def new
    @menu_item = MenuItem.new
  end

  def edit
    @menu_item = MenuItem.find params[:id]
  end

  def show
    @menu_item = MenuItem.find params[:id]
  end

  def update
    menu_item = MenuItem.find params[:id]
    menu_item.update menu_item_params
    redirect_to menu_items_path
  end

  def destroy
    # MenuItem.destroy params[:id]
    # redirect_to menu_items_path

    menu_item = MenuItem.find params[:id]

    if menu_item.orders.any?
      flash[:error] = "Can't 86 menu item - open orders"
      redirect_to menu_items_path
    else
      menu_item.destroy!
      flash[:success] = "You've served all portions - safe to 86"
      redirect_to menu_items_path
    end

  end

  private

  def menu_item_params
    params.require(:menu_item).permit(:name, :description, :price)
  end

  def admin_or_redirect_to_log_in
    unless current_server.admin?
      redirect_to log_in_path
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :get_server_or_redirect_to_log_in

  def index
    @orders = Order.all

  end

  def show
    @order = Order.find params[:id]

  end

  def edit
    @order = Order.find params[:id]

  end

  def update
    order = Order.find params[:id]
    order.update order_params
    redirect_to orders_path

  end

  def new
    @order = Order.new
    @customers = Customer.all
    @menu_items = MenuItem.all

  end

  def create
    order = Order.create!(order_params)

    redirect_to customers_path

  end

  def destroy
    order = Order.find params[:id]
    order.destroy
    redirect_to orders_path

  end

  private

  def order_params
    params.require(:order).permit(:server_id, :menu_item_id, :customer_id)
  end

  def get_server_or_redirect_to_log_in

    if session[:server_id]
      @server = Server.find session[:server_id]
    else
      redirect_to log_in_path
    end

  end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  def new
    @server = Server.new
      unless current_server.admin?
        redirect_to log_in_path
      end
  end

  def create
    unless current_server.admin?
      redirect_to log_in_path
    end

    server = Server.create server_params
    redirect_to log_in_path
  end

  def log_in
  end

  def profile
    if session[:server_id]
      @server = Server.find session[:server_id]
    else
      redirect_to log_in_path
    end

  end

  private

  def server_params
    params.require(:server).permit(:username, :password, :password_confirmation, :admin)
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    username = params[:username]
    password = params[:password]

    server = Server.find_by username: username

    if server && server.authenticate( password )
      session[:server_id] = server.id

      if server.admin?
        redirect_to menu_items_path
      else
        redirect_to profile_path
      end
      
    else
      redirect_to log_in_path
    end
  end

  def destroy
    session[:server_id] = nil
    redirect_to log_in_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_server
    @current_server ||= get_current_server
  end

  def get_current_server
    if session[:server_id]
      Server.find(session[:server_id])
    else
      nil
    end
  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/edit.html.erb
<h1>edit food items - by admin</h1>

app/views/admins/index.html.erb
<h1>full list of food items to be edited by admin - each needs a delete link and an edit link</h1>

app/views/admins/new.html.erb
<h1>New food item that was created by admin </h1>

app/views/admins/show.erb
<h1>List of Menu Items for Admins</h1>

app/views/customers/edit.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
    <li><%= link_to "LOG OUT", deletion_path, method: :delete %><span class="pipes"> | </span></li>
    <li><span class="nav-name">WELCOME BACK <%= current_server.username %></span></li>
  </ul>
</nav>



<h1>EDIT CUSTOMER</h1>

<%= form_for @customer do |f| %>
  <%= f.hidden_field "server_id", :value => @server.id%>

  <span class="form"><%= f.label :table_number %></span>
  <%= f.select( :table_number, options_for_select([[20,20],[21,21],[22,22],[23,23],[24,24],[25,25]] ), {}, { :class => "drop-down-arrow"} ) %>

  <br>
  <br>

  <span class="form"><%= f.label :seat_number %></span>
  <span class="drop-down-arrow"><%= f.select( :seat_number, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8]] ) ) %></span>
  <br>

  <%= submit_tag "EDIT CUSTOMER", class: "button" %>

  <% end %>

app/views/customers/index.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
    <li><%= link_to "LOG OUT", deletion_path, method: :delete %><span class="pipes"> | </span></li>
    <li><%= link_to "START NEW ORDER", new_customer_path %><span class="pipes"> | </span></li>
    <li><span class="nav-name">WELCOME BACK <%= current_server.username %></span></li>
  </ul>
</nav>


<h1>OPEN ORDERS</h1>

<% @customers.each do |customer| %>

    <h4>SEAT NUMBER:   <span class="seat-link"><%= link_to( customer.seat_number, customer_path(customer.id) ) %></h4></span>

    <h4>TABLE NUMBER:   <span class="seat-link"> <%= customer.table_number %></h4></span>

    <h4>HAVE THEY PAID?   <span class="seat-link"> <%= customer.has_paid %></h4></span>

    <h4>FOOD ORDER:  <span class="seat-link"> <% customer.menu_items.each do |menu_item| %>
      <%= render partial: "menu_items/menu_item", locals: {menu_item: menu_item} %>
        <% end %> </h4> </span>
    <br>

    <div style="centerline">
      <%= link_to "MARK AS PAID", customer_path(customer.id), method: :delete %> <span class="pipes">  |  </span>

      <%= link_to "EDIT CUSTOMER INFO", edit_customer_path(customer.id) %> <span class="pipes">  |  </span>

      <%= link_to "ADD FOOD", customer_path(customer.id) %>
    </div>

    <br>
    <hr>

    <% end %>

app/views/customers/new.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
    <li><%= link_to "LOG OUT", deletion_path, method: :delete %><span class="pipes"> | </span></li>
    <li><span class="nav-name">WELCOME BACK <%= current_server.username %></span></li>
  </ul>
</nav>



<h1>CREATE NEW CUSTOMER</h1>

<%= form_for @customer do |f| %>
  <%= f.hidden_field "server_id", :value => @server.id%>
  <span class="form"><%= f.label :table_number %></span>
  <span class="drop-down-arrow"><%= f.select( :table_number, options_for_select([['1','1'],['2','2'],['3','3'],['4','4'],['5','5'],['6','6']] ) ) %></span>
  <br>
  <span class="form"><%= f.label :seat_number %></span>
  <span class="drop-down-arrow"><%= f.select( :seat_number, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8]] ) ) %></span>
  <br>

  <%= submit_tag "CREATE ORDER", class: "button" %>

  <% end %>

  <nav>
    <ul>
      <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
      <li><%= link_to "LOG OUT", deletion_path, method: :delete %></li>
    </ul>
  </nav>

app/views/customers/show.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
    <li><%= link_to "LOG OUT", deletion_path, method: :delete %><span class="pipes"> | </span></li>
    <li><span class="nav-name">WELCOME BACK <%= current_server.username %></span></li>
  </ul>
</nav>

<div class="customer">

<span class="customer-label">TABLE NUMBER:</span> <span class="customer-info"><%= @customer.table_number %></span> <span class="pipes">  |  </span>

<span class="customer-label"> SEAT NUMBER:</span> <span class="customer-info"><%= @customer.seat_number %></span>
</div>

<h1>ADD FOOD</h1>


<%= form_for @order do |f| %>
  <%= f.hidden_field "server_id", :value => @server.id%>
  <%= f.hidden_field "customer_id", :value => @customer.id%>

  <span class="form"><%= f.label :menu_item %></span>
  <%= f.collection_select :menu_item_id, MenuItem.all, :id, :name, class: "custom-dropdown" %>
  <br>

  <%= submit_tag "FINISH ORDER", class: "button" %>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RESTaurant</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <div class="head-logo">
        <ul class="flex-logo">
          <li class="flex-item">R</li>
          <li class="flex-item">E</li>
          <li class="flex-item">S</li>
          <li class="flex-item">T</li>
        </ul>
    </div>

    <div class="body-box">


      <%= yield %>


  </div>

</body>
</html>

app/views/menu_items/_menu_item.html.erb
<br>
<%= menu_item.name %> ...
<%= menu_item.price %>
<br>

app/views/menu_items/edit.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
    <li><%= link_to "LOG OUT", deletion_path, method: :delete %><span class="pipes"> | </span></li>
    <li><span class="nav-name">WELCOME BACK <%= current_server.username %></span></li>
  </ul>
</nav>

<h1>EDIT MENU ITEM </h1>

      <%= form_for @menu_item do |f| %>

        <span class="form"><%= f.label :name %></span>
        <%= f.text_field :name, class:'text-box' %>

        <br>

        <span class="form"><%= f.label :description %></span>
        <%= f.text_field :description, class:'text-box' %>

        <br>

        <span class="form"><%= f.label :price %></span>
        <%= f.number_field :price, class:'text-box' %>

        <br>

        <%= submit_tag "EDIT ITEM", class: "button" %>

      <% end %>

app/views/menu_items/index.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
    <li><%= link_to "LOG OUT", deletion_path, method: :delete %><span class="pipes"> | </span></li>
    <li><span class="nav-name">WELCOME BACK <%= current_server.username %></span></li>
  </ul>
</nav>

<h1>ALL MENU ITEMS </h1>

<% @menu_items.each do |menu_item| %>

    <h2><%= menu_item.name.upcase %></h2>

    <p><%= menu_item.description %> .........
    <%= menu_item.price %></p>

    <%= link_to "DELETE DISH", menu_item_path(menu_item.id), method: :delete %> <span class="pipes">  |  </span>

    <%= link_to "EDIT DISH", edit_menu_item_path(menu_item.id) %>

    <br>
    <hr>

    <% end %>

</div>

    <ul class="body-button">

      <li class="button"> <%= link_to "ADD DISH", new_menu_item_path %> </li>

    </ul>

app/views/menu_items/new.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
    <li><%= link_to "LOG OUT", deletion_path, method: :delete %><span class="pipes"> | </span></li>
    <li><span class="nav-name">WELCOME BACK <%= current_server.username %></span></li>
  </ul>
</nav>



<h1>ADD MENU ITEM</h1>

<%= form_for @menu_item do |f| %>

  <span class="form"><%= f.label :name %></span>
  <%= f.text_field :name, class: 'text-box' %>

  <br>

  <span class="form"><%= f.label :description %></span>
  <%= f.text_field :description, class: 'text-box' %>

  <br>

  <span class="form"><%= f.label :price %></span>
  <%= f.number_field :price, class: 'text-box' %>

  <br>

  <%= submit_tag "ADD ITEM", class: "button" %>

<% end %>

app/views/menu_items/show.html.erb
this page is unused

app/views/orders/edit.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
    <li><%= link_to "LOG OUT", deletion_path, method: :delete %><span class="pipes"> | </span></li>
    <li><span class="nav-name">WELCOME BACK <%= current_server.username %></span></li>
  </ul>
</nav>

<h1>EDIT FOOD</h1>


<%= form_for @order do |f| %>
  <%= f.hidden_field "server_id", :value => @server.id%>
  <%= f.hidden_field "customer_id", :value => @customer.id%>

  <span class="form"><%= f.label :menu_item %></span>
  <%= f.collection_select :menu_item_id, MenuItem.all, :id, :name, class: "custom-dropdown" %>
  <br>

  <%= submit_tag "FINISH ORDER", class: "button" %>

  <% end %>

app/views/orders/index.html.erb
this page is unused

app/views/orders/new.html.erb
this page is unused

app/views/orders/show.html.erb
this page is unused

app/views/servers/log_in.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
  </ul>
</nav>



<div class="form-page-body">
  <h1>LOG IN </h1>


    <%= form_tag '/sessions', method: :post do %>

      <span class="form"><%= label_tag :username %></span>
      <span class="text-box"><%= text_field_tag :username %></span>

      <br>
      <br>

      <span class="form"><%= label_tag :password %></span>
      <span class="text-box"><%= password_field_tag :password %></span>

      <br>

      <%= submit_tag "LOG IN", class: "button" %>

    <% end %>


</div>

app/views/servers/new.html.erb
<div class="form-page-body">

  <h1>NEW SERVER</h1>



    <%= form_for @server do |f| %>

      <span class="form"><%= f.label :username %></span>
      <%= f.text_field :username, class: 'text-box' %>

      <br>

      <span class="form"><%= f.label :password %></span>
      <%= f.password_field :password, class: 'text-box' %>

      <br>

      <span class="form"><%= f.label :password_confirmation %></span>
      <%= f.password_field :password_confirmation, class: 'text-box' %>

      <br>

      <span class="form"><%= f.label :admin %></span>
      <%= f.check_box :admin %>

      <br>

      <%= submit_tag "CREATE SERVER", class: "button" %>

    <% end %>


</div>

app/views/servers/profile.html.erb
<nav class="server-name">
  <ul>
    <li><%= link_to "HOME", :root %> <span class="pipes"> | </span></li>
    <li><%= link_to "LOG OUT", deletion_path, method: :delete %><span class="pipes"> | </span></li>
    <li><span class="nav-name">WELCOME BACK <%= current_server.username %></span></li>
  </ul>
</nav>

<ul class="body-button">

  <li class="button"><%= link_to "LOG OUT", deletion_path, method: :delete %></li>

  <li class="button"><%= link_to "NEW ORDER", new_customer_path, method: :get %></li>

</ul>

app/views/welcome/index.html.erb
  <ul class="body-button">

    <li class="button"><%= link_to "NEW SERVER", new_server_path %></li>

    <li class="button"><%= link_to "LOG IN", log_in_path %></li>

  </ul>